#!/bin/bash

log_dir=~/.local/share/neosh
TIME=`which time`

if [ ! -d $log_dir ]; then
  mkdir -p $log_dir
fi

while :
do
  PWD=`pwd`
  read -ep "$(whoami)@$(hostname):[$(echo "${PWD/#$HOME/\~}")] $ " command
  
  # Check if native command
  help $(echo "$command" | awk '{print $1}') 1> /dev/null 2> $log_dir/.non_native.log

  if [ -z "$(cat $log_dir/.non_native.log)" ]; then
    $command
  else
    $TIME -o $log_dir/.time.log --verbose $command 
  fi
done

