#!/bin/bash

history -r $HOME/.bash_history

trap help_exit SIGINT
trap finish EXIT

function help_exit {
  echo -e "\nTo exit the shell, use the command \`exit\`"
}

function finish {
  history -w $HOME/.bash_history
}

log_dir=~/.local/share/neosh

if [ ! -d $log_dir ]; then
  mkdir -p $log_dir
fi

while :
do
  PWD=`pwd`
  read -ep "$(whoami)@$(hostname):[$(echo "${PWD/#$HOME/\~}")] $ " cmd

  # Check if native command
  help $(echo "$cmd" | awk '{print $1}') 1> /dev/null 2> $log_dir/.non_native.log

  if [ -z "$(cat $log_dir/.non_native.log)" ]; then
    eval $cmd

    history -s "$cmd"
  else
    command time -ao $log_dir/.time.log --verbose sh -c "$cmd"

    history -s "$cmd"
  fi
done

